// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwoZpSvuWm-UYHqBvvOLRd8BGowPrw8Bo',
    appId: '1:505492971401:web:4bf128472207695c208b58',
    messagingSenderId: '505492971401',
    projectId: 'jopetrol-f161d',
    authDomain: 'jopetrol-f161d.firebaseapp.com',
    storageBucket: 'jopetrol-f161d.appspot.com',
    measurementId: 'G-FBWNVW7RTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bbpkSqMnyNu-fyXYvqtvxIsMXguhLA8',
    appId: '1:505492971401:android:27a9612cbd53101a208b58',
    messagingSenderId: '505492971401',
    projectId: 'jopetrol-f161d',
    storageBucket: 'jopetrol-f161d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvXypYqT1LJ6T2Sg4PzbzDFhtjvIw5N7c',
    appId: '1:505492971401:ios:62a7f3f7b5486819208b58',
    messagingSenderId: '505492971401',
    projectId: 'jopetrol-f161d',
    storageBucket: 'jopetrol-f161d.appspot.com',
    iosBundleId: 'com.example.flutterJo',
  );
}
